# Generated by Django 5.1 on 2024-10-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id_producto', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=30)),
                ('tipo_prod', models.CharField(max_length=20)),
                ('cant_prod', models.IntegerField()),
                ('metodo_pag', models.CharField(max_length=10)),
                ('proveedor_prod', models.CharField(max_length=20)),
                ('id_proveedor', models.IntegerField()),
            ],
        ),
    ]
